const path = require('path')

const ST_CONTRACT_DIR = path.dirname(__dirname) + '/contracts/'

const ST_STORAGE_FILENAME = 'storage.sol'
const ST_STORAGE_CONTRACT_NAME = 'EIP1153Skeleton'
const ST_EVM_FILENAME = 'evm.sol'
const ST_EVM_CONTRACT_NAME = 'EVM'
const ST_CROSS_EVM_FILENAME = 'evm.sol'
const ST_CROSS_EVM_CONTRACT_NAME = 'CrossEVM'
const ST_GOVERNANCE_FILENAME = 'governance.sol'
const ST_GOVERNANCE_CONTRACT_NAME = 'Governance'

const ST_GOVERNANCE_NODE_MANAGER_ADDRESS = "0x0000000000000000000000000000000000001001"
const ST_GOVERNANCE_COUNCIL_ADDRESS = "0x0000000000000000000000000000000000001002"

const PROPOSAL_TYPE_COUNCIL_ELECT = 0
const PROPOSAL_TYPE_NODE_UPDATE = 1
const PROPOSAL_TYPE_NODE_ADD = 2
const PROPOSAL_TYPE_NODE_REMOVE = 3


module.exports = {
    ST_CONTRACT_DIR,
    ST_STORAGE_FILENAME,
    ST_STORAGE_CONTRACT_NAME,
    ST_EVM_FILENAME,
    ST_EVM_CONTRACT_NAME,
    ST_CROSS_EVM_FILENAME,
    ST_CROSS_EVM_CONTRACT_NAME,
    ST_GOVERNANCE_FILENAME,
    ST_GOVERNANCE_CONTRACT_NAME,
    ST_GOVERNANCE_NODE_MANAGER_ADDRESS,
    ST_GOVERNANCE_COUNCIL_ADDRESS,
    PROPOSAL_TYPE_COUNCIL_ELECT,
    PROPOSAL_TYPE_NODE_ADD,
    PROPOSAL_TYPE_NODE_REMOVE,
    PROPOSAL_TYPE_NODE_UPDATE
}
